name: Publish Docker Images

on:
  push:
    branches:
      - 'main'
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        service:
          - name: frontend
            context: ./worklenz-frontend
            container_name: worklenz-frontend
          - name: backend
            context: ./worklenz-backend
            container_name: worklenz-backend

    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service.container_name }}
          flavor: |
            latest=true

          tags: |
            type=raw,value=latest
            type=ref,event=tag
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
